export default function DisclaimerPage() {
  return (
    <div className="min-h-screen pt-24 pb-20 px-6" style={{ background: 'var(--navy)' }}>
      <div className="max-w-3xl mx-auto">
        <div className="section-label mb-4">Legal</div>
        <h1 className="mb-2">Disclaimer</h1>
        <p className="mb-12 text-sm font-mono" style={{ color: 'var(--muted)' }}>Last updated: April 2026</p>

        <div className="prose-groundwork space-y-8" style={{ color: 'var(--text-secondary)' }}>
          <section>
            <h2>Not Professional Advice</h2>
            <p>All content on Groundwork BHS — including guides, permit information, cost estimates, BOQs, and AI Advisor responses — is provided for general informational purposes only. Nothing on this platform constitutes legal, financial, architectural, engineering, or professional advice of any kind.</p>
          </section>
          <section>
            <h2>AI Advisor Limitations</h2>
            <p>The Groundwork AI Advisor draws on publicly available Bahamian laws, building codes, permit processes, and construction standards. It may not reflect recent regulatory changes, local variances, or your specific site conditions. AI responses should be verified with the relevant Bahamian government authority or a licensed professional before you rely on them.</p>
          </section>
          <section>
            <h2>Cost Estimates and BOQs</h2>
            <p>All cost estimates and Bills of Quantities generated by Groundwork BHS are approximations based on general Nassau and Family Island market rates. Actual costs will vary based on contractor pricing, material availability, site conditions, and timing. Groundwork BHS is not liable for discrepancies between estimated and actual construction costs.</p>
          </section>
          <section>
            <h2>Contractor Listings</h2>
            <p>Groundwork BHS does not verify the license, insurance, quality, or current status of contractors listed in the directory. Always independently verify a contractor&apos;s qualifications before entering into any agreement.</p>
          </section>
          <section>
            <h2>No Warranty</h2>
            <p>This platform and its content are provided &quot;as is&quot; without any warranty, express or implied. We do not warrant the accuracy, completeness, or fitness for a particular purpose of any information on this platform.</p>
          </section>
          <section>
            <h2>Professional Consultation</h2>
            <p>For legal matters, consult a licensed Bahamian attorney. For land surveys, consult a registered Bahamian surveyor. For structural matters, consult a licensed engineer. For financial matters, consult a registered financial advisor or your bank.</p>
          </section>
          <section>
            <h2>Contact</h2>
            <p>For questions: <a href="mailto:info@groundworkbhs.com" style={{ color: 'var(--cyan)' }}>info@groundworkbhs.com</a></p>
          </section>
        </div>
      </div>
    </div>
  )
}
